name: Build and Published NPM Package

on:
  push:
    tags: [ '*.*.*' ]
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    # Verifica se está na branch master
    if: github.ref == 'refs/heads/master'

    steps:
      # Fazendo Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # Instalando NodeJs
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/

      # Instalando dependências
      - name: Install dependencies
        run: npm install

      # Executando build dos components
      - name: Build
        run: npm run build

      # Publica pacote no NPM
      - name: Publish NPM
        working-directory: ./dist
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}